### PR TITLE
Workers with xylem::docker also need gluster::client

### PR DESCRIPTION
**Pull request by jerith**

### CODE REVIEW

**Comment by JayH5** [comment]
Is it still going to be possible for this to be set up on the standalone VM?

**Comment by jerith** [comment]
> Is it still going to be possible for this to be set up on the standalone VM?

Good point. It should (because `gluster` and `gluster::client` shouldn't conflict), but I need to test that.

**Comment by jerith** [comment]
> Is it still going to be possible for this to be set up on the standalone VM?

It does if we're clever about how we use it. There's no conflict in the package, but the `seed_stack::xylem` class needs to be parsed before the `seed_stack::worker` class otherwise they both try to declare `gluster::repo`.

**Comment by JayH5** [comment]
:+1:

**Comment by JayH5** [comment]
:+1:

**Comment by JayH5** [comment]
I think you need to add a test or two for the new parameter

**Comment by JayH5** [comment]
:+1:

**Pull request merged**
