### PR TITLE
Add health checks for services registered in Consul

### PR DESCRIPTION
**Pull request by JayH5**
- Mesos
- Marathon
- Zookeeper

### CODE REVIEW

**Comment by jerith** [comment]
:+1: if you've tested the actual health checks. :-)

**Comment by JayH5** [comment]
_sigh_ Zookeeper is broken in some weird way :cry:
For tomorrow...

**Comment by JayH5** [comment]
@jerith: Ready for re-review. This has been tested now :)

**Comment by jerith** [comment]
:+1:

**Pull request merged**
